import dbConnect from "@/lib/db";
import Project from "@/model/Project";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();

    await dbConnect();

    // Create project (slug will be auto-generated by pre-save hook)
    const normalizeList = (value: unknown) =>
      Array.isArray(value)
        ? value.map((item) => String(item).trim().toLowerCase()).filter(Boolean)
        : typeof value === "string"
          ? value
              .split(",")
              .map((item) => item.trim().toLowerCase())
              .filter(Boolean)
          : [];

    const project = await Project.create({
      title: data.title,
      description: data.description,
      thumbnail: data.thumbnail,
      gitRepo: data.gitRepo,
      liveLink: data.liveLink,
      category: normalizeList(data.category),
      tech: normalizeList(data.tech),
      builder: data.builder,
      status: "pending",
    });

    return NextResponse.json({
      success: true,
      project: {
        id: project._id,
        slug: project.slug,
        title: project.title,
      },
    });
  } catch (error) {
    console.error("Project creation error:", error);
    return NextResponse.json(
      { error: "Failed to create project" },
      { status: 500 }
    );
  }
}

export async function GET(req: NextRequest) {
  try {
    await dbConnect();

    const searchQuery = req.nextUrl.searchParams.get("q")?.trim();
    const categoryParam = req.nextUrl.searchParams.get("category")?.trim();
    const pageParam = req.nextUrl.searchParams.get("page");
    const limitParam = req.nextUrl.searchParams.get("limit");
    const page = Math.max(1, Number(pageParam) || 1);
    const limit = Math.min(50, Math.max(1, Number(limitParam) || 10));

    const filter: Record<string, unknown> = { status: "approved" };

    if (searchQuery) {
      const escapedQuery = searchQuery.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const textRegex = new RegExp(escapedQuery, "i");
      filter.$or = [
        { title: { $regex: textRegex } },
        { "builder.username": { $regex: textRegex } },
      ];
    }

    if (categoryParam) {
      const categories = categoryParam
        .split(",")
        .map((category) => category.trim())
        .filter(Boolean);

      if (categories.length > 0) {
      const categoryRegexes = categories.map((category) => {
        const escaped = category.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        return new RegExp(`(^|[\\s,])${escaped}([\\s,]|$)`, "i");
      });
      filter.category = { $in: categoryRegexes };
    }
    }

    const total = await Project.countDocuments(filter);
    const projects = await Project.find(filter)
      .sort({ loves: -1, views: -1, createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit);

    if (!projects) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    return NextResponse.json({
      projects,
      total,
      page,
      limit,
    });
  } catch (error) {
    console.error("Get project error:", error);
    return NextResponse.json(
      { error: "Failed to fetch project" },
      { status: 500 }
    );
  }
}
