import dbConnect from "@/lib/db";
import Project from "@/model/Project";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();

    await dbConnect();

    // Create project (slug will be auto-generated by pre-save hook)
    const project = await Project.create({
      title: data.title,
      description: data.description,
      thumbnail: data.thumbnail,
      gitRepo: data.gitRepo,
      liveLink: data.liveLink,
      category: data.category,
      tech: data.tech,
      builder: data.builder,
      status: "pending",
    });

    return NextResponse.json({
      success: true,
      project: {
        id: project._id,
        slug: project.slug,
        title: project.title,
      },
    });
  } catch (error) {
    console.error("Project creation error:", error);
    return NextResponse.json(
      { error: "Failed to create project" },
      { status: 500 }
    );
  }
}

export async function GET(req: NextRequest) {
  try {
    await dbConnect();

    // Look up approved project by slug or MongoDB _id
    const projects = await Project.find({
      status: "approved",
    });

    if (!projects) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    return NextResponse.json(projects);
  } catch (error) {
    console.error("Get project error:", error);
    return NextResponse.json(
      { error: "Failed to fetch project" },
      { status: 500 }
    );
  }
}
