import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Project details",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto w-full md:w-5/6 lg:w-3/4 my-8  mt-16 mb-8 min-h-screen px-4 lg:px-0">
      {children}
    </div>
  );
}
