import type { Metadata } from "next";
import { Geist, Geist_Mono, Google_Sans_Code, Ubuntu } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { FingerprintProvider } from "@/contexts/FingerprintContext";
import AuthSessionProvider from "@/components/providers/SessionProvider";

const geistSans = Ubuntu({
  variable: "--font-sans-code",
  subsets: ["cyrillic"],
  style: ["normal"],
  weight: ["300"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rialo Build Showcase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="rialodark">
      <body className={`${geistSans.variable} antialiased`}>
        <FingerprintProvider>
          <AuthSessionProvider>
            <Header />
            {children}
            <Footer />

            <div id="portal"></div>
          </AuthSessionProvider>
        </FingerprintProvider>
      </body>
    </html>
  );
}
